version: '3.6'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    container_name: iam_svc_pgdb
    environment:
      POSTGRES_USER: iam
      POSTGRES_PASSWORD: iam
      POSTGRES_DB: iam
    ports:
      - 5433:5432
